# Generated by Django 4.2.1 on 2023-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apple',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='apple',
            name='long',
        ),
        migrations.AddField(
            model_name='apple',
            name='geolocation',
            field=models.CharField(default=(0, 0), max_length=100),
            preserve_default=False,
        ),
    ]
