# Generated by Django 4.2.1 on 2023-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_reg', '0002_remove_apple_lat_remove_apple_long_apple_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apple',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='apple',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apple',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
