# Generated by Django 4.2.1 on 2023-06-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple_reg', '0003_remove_apple_geolocation_apple_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apple',
            name='longitude',
        ),
    ]
