# Generated by Django 4.2.1 on 2023-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_reg', '0004_remove_apple_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
