# Generated by Django 4.2.1 on 2023-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_reg', '0005_apple_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apple',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='apple',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
